### PR TITLE
add install-llc 

### PR DESCRIPTION
**Pull request by goloveychuk**

### CODE REVIEW

**Comment by yurydelendik** [comment]
thanks

**Comment by goloveychuk** [comment]
@yurydelendik 
Looks like you know much about llvm and wasm.
I'm trying to build swift to wasm.
Achieved small success and faced with problem, that swift using `swiftcc` calling convention.
But wasm support only `c` convention.
https://llvm.org/docs/LangRef.html#calling-conventions
Do you know, is it really possible to bring swifcc convention to wasm?

**Comment by yurydelendik** [comment]
> Do you know, is it really possible to bring swifcc convention to wasm?

I don't. I see Rust is trying to use the notation close to C. Is there a way to define exported swift function as C notation?

**Comment by goloveychuk** [comment]
Actually I can replace here
https://github.com/apple/swift/blob/master/lib/IRGen/GenCall.cpp#L137-L160
This could work if swiftcc using mostly for obj-c  bridging .

**Pull request merged**
